config/routes.rb
Rails.application.routes.draw do
  get 'select_role/edit', as: 'select_role'
  post 'select_role/update'

  resources :roles
  root to: "landing#index"
  get 'landing/index'

  devise_for :users

  resources :users
  resources :messages
  resources :waitings
  resources :tasks do
    member do
      get :begin
      get :finish
    end
  end
  resources :my_processes do
    member do
      get :success
      get :new_tasks
      patch :create_tasks
      patch :finish
    end
  end
  resources :process_types

  # Omiauth for twitter
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'


  # Tests routes, can be deleted
  get '/test', to: 'tests#index'
  get '/workers', to: 'workers#index', as: 'workers'
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessor :dont_validate_start_and_end

  belongs_to :my_process
  belongs_to :user
  belongs_to :responsible_user, class_name: 'User', foreign_key: 'responsible_user_id'

  has_one :process_type, through: :my_process
  has_many :waitings, class_name: 'Waiting', foreign_key: 'task_id', dependent: :destroy
  has_many :waiting_for_tasks, through: :waitings, source: :waiting

  has_many :dependent_waitings, class_name: 'Waiting', foreign_key: 'waiting_id', dependent: :destroy
  has_many :tasks_waiting, through: :dependent_waitings, source: :task

  has_and_belongs_to_many :roles

  geocoded_by :address
  before_validation :geocode, if: :address_changed?
  before_create :assign_start_and_end

  validates :name, :latitude, :longitude, presence: true

  scope :sorted_by_assigned_start, -> { all.sort {|t1, t2| t1.assigned_start <=> t2.assigned_start} }

  before_save :rearrange_waiting_tasks

  def self.order_by(tasks, params)
    case params[:order]
      when "distance"
        location = Geocoder.search(params[:ip])
        current_lat = location[0].data['latitude']
        current_long = location[0].data['longitude']
        ans = []

        tasks.each do |task|
          the_closest = Task.closest(tasks, current_lat, current_long)
          ans << the_closest
          tasks = tasks.where("id != ?", the_closest.id)
          current_lat = the_closest.latitude
          current_long = the_closest.longitude
        end
        return ans
      when "priority"
        return tasks.order("priority ASC")
      when "assigned_start"
        return tasks.order("assigned_start ASC")
      else
        return tasks.order("assigned_start ASC")
    end
  end

  def self.closest(tasks, lat, long)
    min = nil
    closest = nil
    tasks.each do |task|
      distance = Math.sqrt((task.latitude-lat.to_f)**2 + (task.longitude-long.to_f)**2)
      if !min or distance < min
        closest = task
        min = distance
      end
    end

    return closest
  end

  def rearrange_waiting_tasks
    waitings = Waiting.where(waiting_id: id)
    waitings.each do |waiting|
      waiting.rearrange_tasks
    end
    if self.waiting_for_tasks.empty?
      self.assign_start_and_end
    end
  end

  def relative_id
    sorted = my_process.tasks.sort {|t1, t2| t1.assigned_start <=> t2.assigned_start}
    sorted.map(&:id).index(self.id).to_i+1
  end

  def status
    if actual_start.blank?
      return 'not-started'
    elsif actual_end.present?
      return 'ended'
    else
      return 'in-progress'
    end
  end

  def human_status
    case self.status
    when 'not-started'
      return 'Waiting'
    when 'ended'
      return 'Ended'
    when 'in-progress'
      return 'In progress'
    end

  end

  def to_s
    prefix = "<b>#{responsible_user || '@ ?'}</b> <small>must </small><b>#{name}</b> <small>at</small> <b>#{address}</b>"
    waiting_for = waiting_for_tasks.any? ? " <small>when</small> <b>#{waiting_for_tasks.map{|task| task.name}.join(', ')}</b> <small>finishes</small>" : ''
    return prefix+waiting_for
  end

  def doable?(user)
    waiting_for_tasks.where('tasks.actual_end IS NULL').blank? and (actual_start.nil? or responsible_user == user)
  end


  def location
    return {lat: latitude, lng: longitude, title: "#{name}", task_id: id,  relative_id: self.relative_id}
  end

  def waitings_to_s
    if waiting_for_tasks.any?
      names = waiting_for_tasks.map{ |task| task.name }
      pluralized_names = (names.length >= 2) ?  ": [#{names.join(', ')}]" : " #{names.first}"
      ", when #{pluralized_names} finishes Hello"
    end
  end

  def assign_start_and_end
    oldest_task = self.my_process.tasks.order("assigned_start ASC").first
    if oldest_task.present?
      self.assigned_start = oldest_task.assigned_start
      self.assigned_end = oldest_task.assigned_end
    else
      self.assigned_start = DateTime.now
      self.assigned_end = DateTime.now+1.hour
    end
  end

  def self.waiting_for_tasks_ids(task, ids)
    waitings = Waiting.where(task: task)

    if waitings.any?
      ids += waitings.pluck :waiting_id
      waitings.each do |waiting|
        ids += self.waiting_for_tasks_ids(waiting.waiting, ids)
      end
    end

    return ids.uniq
  end

  def visible_for(user)
    return (user.role?(:admin) or self.roles.empty? or (self.roles.pluck(:name) & user.roles.pluck(:name)).any?)
  end

  def self.visibles_for(user)
    if user.role == 'admin'
      self.all
    else
      Task.joins('LEFT JOIN roles_tasks ON tasks.id = roles_tasks.task_id')
      .where('roles_tasks.task_id IS NULL OR roles_tasks.role_id IN (?)', user.roles.pluck(:id))
      .uniq
    end
  end

  def self.waiting_tasks_ids(task, ids)
    waitings = Waiting.where(waiting_id: task)

    if waitings.any?
      ids += waitings.pluck :task_id
      waitings.each do |waiting|
        ids += self.waiting_tasks_ids(waiting.task, ids)
      end
    end

    return ids.uniq
  end

  def can_wait_for
    my_process.tasks.where.not(id: Task.waiting_tasks_ids(self, [])+[self.id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :begin, :finish]

  def index
    @tasks = Task.where("user => ? OR responsible_user", current_user, current_user).order('created_at DESC')
  end

  def show
  end

  def begin
    message = "##{@task.my_process.hashtag} #{@task.name} started now at #{@task.address}".first(140)
    Message.create(sender: current_user, message: message)
    @task.update_attributes actual_start: DateTime.now, responsible_user_id: current_user.id
    current_user.update_attributes(latitude: @task.latitude, longitude: @task.longitude)
    redirect_to @task.my_process
  end

  def finish
    Message.create(sender: current_user, message: "##{@task.my_process.hashtag} #{@task.name} ended")
    @task.update_attribute :actual_end, DateTime.now
    redirect_to @task.my_process
  end

  def new
    @task = Task.new(my_process_id: params[:my_process_id])
  end

  def edit
  end

  def create
    create_params = task_params
    create_params.delete(:waiting_for_task_ids)
    @task = Task.new(create_params)

    if @task.save
      @task.update(waiting_for_task_ids: task_params[:waiting_for_task_ids])
      redirect_to @task.my_process
    else
      redirect_to MyProcess.find(task_params[:my_process_id]), notice: "#{@task.errors.full_messages.first} -> #{create_params[:waiting_for_task_ids]}"
    end
  end

  def update
    if @task.update(task_params)
      redirect_to my_process_path(@task.my_process, anchor: "task-#{@task.id}")
    else
      redirect_to my_process_path(@task.my_process, anchor: "task-#{@task.id}")
    end
  end

  def destroy
    my_process = @task.my_process
    @task.destroy
    respond_to do |format|
      format.html{ redirect_to my_process }
      format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(
        :name,
        :my_process_id,
        :work_link,
        :work_description,
        :priority,
        :user_id,
        :address,
        :latitude,
        :longitude,
        :assigned_start,
        :assigned_end,
        :responsible_user_id,
        :description,
        :waiting_for_task_ids => [],
        :role_ids => []
      )
    end
end

app/views/tasks/_fields.haml
_fields.haml

app/views/tasks/_form.html.haml
- if current_user.role? :admin
  = simple_form_for task do |f|
    .form-inputs
      - if !f.object.new_record?
        %h3= "#{f.object.relative_id}) #{f.object.name}"
      .row
        .col-xs-12.col-md-6
          = f.input :name
          = f.input :responsible_user, disabled: true, input_html: {class: 'disable'}
          %label= "Start: #{datetime f.object.actual_start} / End: #{datetime f.object.actual_end}"
          = f.input :address
          = f.input :link, label: 'Admin Link'
          = f.input :description, input_html: {class: 'width-100', style: 'height: 77px'}, label: 'Admin Description'
          = f.input :work_link
          = f.input :work_description, input_html: {class: 'width-100', style: 'height: 77px'}
          = f.association :my_process, as: :hidden
          %b Waiting for:
          = f.object.waiting_for_tasks.pluck :name
          %br
          %b Tasks waiting:
          = f.object.tasks_waiting.pluck :name
        .col-xs-12.col-md-6
          = f.input :priority, collection: (1..10).to_a, include_blank: '-- Select priority --'
          = f.association :roles, as: :check_boxes, roles: 'Roles'
          = f.association :waiting_for_tasks, as: :check_boxes, collection: task.can_wait_for
    %hr
    .form-actions
      = link_to 'Close', '#', class: 'btn btn-default close-task-form'
      = f.button :submit, class: 'btn btn-primary pull-right'
      .clearfix
- else
  = simple_form_for task do |f|
    %h3= "#{f.object.relative_id}) #{f.object.name}"
    %table.table{style: 'margin-bottom: 0'}
      %tr
        %td Start
        %td= "#{task.actual_start || '-'}"
      %tr
        %td End
        %td= "#{task.actual_end || '-'}"
      %tr
        %td Admin escription
        %td= task.description
      %tr
        %td Admin Link
        %td
          - if task.link
            = link_to task.link, task.link
      %tr
        %td Work Link
        %td= f.input :work_link, label: false
      %tr
        %td Work Description
        %td= f.input :work_description, label: false, input_html: {style: 'width: 100%'}
    = f.submit class: 'btn btn-default pull-right'
    .clearfix
    %hr
    = link_to 'Close', '#', class: 'btn btn-default close-task-form'
    - if task.actual_start.present?
      = link_to 'End task', finish_task_path(task), class: "btn btn-primary pull-right #{'disabled' if task.actual_end.present?}"
    - else
      = link_to 'Start task', begin_task_path(task), class: 'btn btn-primary pull-right'
.mb-lg

app/views/tasks/edit.html.haml
.row
  .col-xs-12.col-md-8.col-md-offset-2
    %h1 Editing task
    = render 'form'

app/views/tasks/index.html.haml
%h1 Listing tasks

%table.table
  %thead
    %tr
      %th Process Type
      %th Process
      %th User
      %th Responsible user
      %th Name
      %th Description
      %th Address
      %th Latitude
      %th Longitude
      %th Starts at
      %th Ends at
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.process_type
        %td= task.my_process
        %td= task.user
        %td= task.responsible_user
        %td= task.name
        %td= task.description
        %td= task.address
        %td= task.latitude
        %td= task.longitude
        %td= task.starts_at
        %td= task.ends_at
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path