config/routes.rb
Rails.application.routes.draw do
  get 'select_role/edit', as: 'select_role'
  post 'select_role/update'

  resources :roles
  root to: "landing#index"
  get 'landing/index'

  devise_for :users

  resources :users
  resources :messages
  resources :waitings
  resources :tasks do
    member do
      get :begin
      get :finish
    end
  end
  resources :my_processes do
    member do
      get :success
      get :new_tasks
      patch :create_tasks
      patch :finish
    end
  end
  resources :process_types

  # Omiauth for twitter
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'


  # Tests routes, can be deleted
  get '/test', to: 'tests#index'
  get '/workers', to: 'workers#index', as: 'workers'
end

app/views/shared/_color_reference.haml
.mt-md
  .can-be-done.inline-block.mr-md Can be done
  .cannot-be-done.inline-block.mr-md In progress or waiting for other tasks to end

app/views/shared/_form_modal.haml
- object_name = object.class.to_s
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", :id => "#{object_name.underscore}-modal-#{object.id}"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        - if object_name == 'Task'
          = link_to object, class: 'btn btn-xs btn-danger', style: 'margin-right: 5px', method: :delete, data: { confirm: 'Are you sure?' } do
            %i.glyphicon.glyphicon-trash
            Delete
        %h4#myModalLabel.modal-title.inline-block= "#{object.class.to_s}"
      .modal-body
        = render "#{object_name.underscore.pluralize}/form", "#{object_name.underscore}".to_sym => object

app/views/shared/_modal.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", :id => "task-modal-#{task.id}"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Update task
      .modal-body
        = render 'tasks/form', task: task

app/views/shared/_navbar.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Geo Workflow
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        - if can? :create, MyProcess and user_signed_in?
          %li
            = link_to new_my_process_path do
              + New process
        - if can? :manage, Role and user_signed_in?
          %li
            = link_to 'Roles', roles_path
        - if can? :read, User
          %li
            = link_to 'Users', users_path
        - if can? :index, MyProcess and user_signed_in?
          %li
            = link_to 'Processes', my_processes_path
        - if can? :create, MyProcess and user_signed_in?
          %li
            = link_to 'Workers', workers_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to current_user.name, 'javascript: return'
          %li
            = link_to destroy_user_session_path, method: :delete do
              %i.glyphicon.glyphicon-off
        - else
          %li
            = link_to 'Signin with twitter', '/auth/twitter'

app/views/shared/_pin_modal.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", :id => "pin-modal-#{pin[:id]}"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true", "id" => "close-multiple-tasks"} ×
        %h4#myModalLabel.modal-title.inline-block= "#{pin[:task_count]} Tasks"
      .modal-body
        %ul
          - pin[:tasks].each do |task|
            %li= link_to "#{task.relative_id}) #{task.name}", "javascript: showTaskForm(#{task.id });$('#close-multiple-tasks').click();"