config/routes.rb
Rails.application.routes.draw do
  get 'select_role/edit', as: 'select_role'
  post 'select_role/update'

  resources :roles
  root to: "landing#index"
  get 'landing/index'

  devise_for :users

  resources :users
  resources :messages
  resources :waitings
  resources :tasks do
    member do
      get :begin
      get :finish
    end
  end
  resources :my_processes do
    member do
      get :success
      get :new_tasks
      patch :create_tasks
      patch :finish
    end
  end
  resources :process_types

  # Omiauth for twitter
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'


  # Tests routes, can be deleted
  get '/test', to: 'tests#index'
  get '/workers', to: 'workers#index', as: 'workers'
end

app/models/waiting.rb
class Waiting < ActiveRecord::Base
  belongs_to :task
  belongs_to :waiting, class_name: 'Task', foreign_key: 'waiting_id'
  validates :task, :waiting, presence: true

  after_create :rearrange_tasks

  def rearrange_tasks
    if waiting.assigned_end > task.assigned_start
      task.assigned_start = waiting.assigned_end
    end
    if (task.assigned_end - task.assigned_start)/60 <= 10
      task.assigned_end = task.assigned_start + 1.hour
    end
    task.dont_validate_start_and_end = true
    task.save
    waitings = Waiting.where(waiting_id: task.id)

    waitings.each do |waiting|
      waiting.rearrange_tasks
    end
  end
end

app/controllers/waitings_controller.rb
class WaitingsController < ApplicationController
  before_action :set_waiting, only: [:show, :edit, :update, :destroy]

  def index
    @waitings = Waiting.all
  end

  def show
  end

  def new
    @waiting = Waiting.new(task_id: params[:task_id])
    @task = @waiting.task
    
    excluded_tasks_ids = [@task.id]
    excluded_tasks_ids += Task.waiting_for_tasks_ids(@task, [])
    excluded_tasks_ids += Task.waiting_tasks_ids(@task, [])
    
    @waitable_tasks = Task.where(my_process: @task.my_process).where.not(id: excluded_tasks_ids)
  end

  def edit
  end

  def create
    @waiting = Waiting.new waiting_params

    if @waiting.save
      redirect_to my_process_path(@waiting.task.my_process, anchor: "task-#{@waiting.task.id}")
    else
      render :new
    end    
  end

  def update
    respond_to do |format|
      if @waiting.update(waiting_params)
        format.html { redirect_to @waiting, notice: 'Waiting was successfully updated.' }
        format.json { render :show, status: :ok, location: @waiting }
      else
        format.html { render :edit }
        format.json { render json: @waiting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @waiting.destroy
    respond_to do |format|
      format.html { redirect_to waitings_url, notice: 'Waiting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_waiting
      @waiting = Waiting.find(params[:id])
    end

    def waiting_params
      params.require(:waiting).permit(:task_id, :waiting_id)
    end
end

app/views/waitings/_form.html.haml
= simple_form_for @waiting do |f|
  .form-inputs
    = f.association :task, as: :hidden
    = f.association :waiting, collection: @waitable_tasks, include_blank: false, label: false, input_html: {class: 'block width-100'}
  %hr
  .form-actions
    = link_to 'Cancel', @task.my_process, class: 'btn btn-default'
    = f.button :submit, class: 'btn btn-primary pull-right'

app/views/waitings/edit.html.haml
%h1 Editing waiting

= render 'form'

= link_to 'Show', @waiting
\|
= link_to 'Back', waitings_path

app/views/waitings/index.html.haml
%h1 Listing Waitings

%table.table
  %thead
    %tr
      %th Task
      %th Waiting
      %th
      %th
      %th

  %tbody
    - @waitings.each do |waiting|
      %tr
        %td= waiting.task
        %td= waiting.waiting
        %td= link_to 'Show', waiting
        %td= link_to 'Edit', edit_waiting_path(waiting)
        %td= link_to 'Destroy', waiting, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Waiting', new_waiting_path

app/views/waitings/new.html.haml
.center
  %h1= "#{@task.name} must wait for"
  = render 'form'

app/views/waitings/show.html.haml
%p#notice= notice

%p
  %b Task:
  = @waiting.task
%p
  %b Waiting:
  = @waiting.waiting

= link_to 'Edit', edit_waiting_path(@waiting)
\|
= link_to 'Back', waitings_path