config/routes.rb
Rails.application.routes.draw do
  get 'select_role/edit', as: 'select_role'
  post 'select_role/update'

  resources :roles
  root to: "landing#index"
  get 'landing/index'

  devise_for :users

  resources :users
  resources :messages
  resources :waitings
  resources :tasks do
    member do
      get :begin
      get :finish
    end
  end
  resources :my_processes do
    member do
      get :success
      get :new_tasks
      patch :create_tasks
      patch :finish
    end
  end
  resources :process_types

  # Omiauth for twitter
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'


  # Tests routes, can be deleted
  get '/test', to: 'tests#index'
  get '/workers', to: 'workers#index', as: 'workers'
end

app/controllers/my_processes_controller.rb
class MyProcessesController < ApplicationController
  before_action :set_my_process, only: [:create_tasks, :new_tasks, :show, :edit, :update, :destroy, :success, :finish]

  def index
    @my_processes = MyProcess.visibles_for(current_user).paginate(page: params[:page], per_page: 15).order('created_at DESC')
  end

  def success
  end

  def finish
    @my_process.update_attribute :status, 'finished'
    Message.create(sender: current_user, message: "##{@my_process.hashtag} ended")
    redirect_to @my_process, notice: 'Process finished. Twitter message sent. You can still edit this process'
  end

  def show
    if current_user.role == 'worker'
      render :show_worker
    elsif current_user.role == 'admin'
      render :show_admin
    else
      render text: 'An admin must approve you'
    end
  end

  def new
    @my_process = MyProcess.new
  end

  def edit
  end

  def create
    @my_process = MyProcess.new(my_process_params)
    @my_process.user = current_user

    if @my_process.save
      redirect_to @my_process
    else
      render :new
    end
  end

  def new_tasks
  end

  def create_tasks
    @my_process.update(my_process_params)
    redirect_to my_process_path(@my_process)
  end

  def update
    if @my_process.update(my_process_params)
      redirect_to @my_process
    else
      render :edit
    end
  end

  def destroy
    @my_process.destroy
    respond_to do |format|
      format.html { redirect_to my_processes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_my_process
      @my_process = MyProcess.find(params[:id])
    end

    def my_process_params
      params.require(:my_process).permit(:name, :hashtag, tasks_attributes: [:id, :name, :address, :assigned_start, :assigned_end])
    end
end

app/views/my_processes/_form.html.haml
= simple_form_for my_process do |f|
  .form-inputs
    = f.input :name
    = f.input :hashtag

  %hr
  
  .form-actions
    = link_to 'Close', my_process, class: 'btn btn-default'
    = f.button :submit, class: 'btn btn-primary pull-right'
    .clearfix

app/views/my_processes/_task_fields.haml
.task-fields.fieldset
  = link_to 'javascript:void(0);', class: 'remove-fieldset pull-right' do
    Remove
    %i.glyphicon.glyphicon-remove-circle
  .clearfix.mb-md
  .row
    .col-xs-12
      = f.input :name, label: 'Task Name'
      = f.input :address, label: 'Task Location / Address', as: :hidden

app/views/my_processes/_work_to_do.haml
.header
  %h1.no-margin.inline-block Work to do
  .pull-right
    %label: Order:
    = link_to 'Best Route', my_process_path(order: 'distance'), class: "btn btn-xs #{'btn-primary' if params[:order]== 'distance'}"
    = link_to 'Priority', my_process_path(order: 'priority'), class: "btn btn-xs #{'btn-primary' if params[:order]== 'priority'}"
    = link_to 'Time', my_process_path(order: 'assigned_at'), class: "btn btn-xs #{'btn-primary' if params[:order]== 'assigned_at'}"
  .clearfix
.mt-lg
  - Task.order_by(@my_process.tasks.visibles_for(current_user), order: params[:order], ip: request.ip).each_with_index do |task, index|
    .task-block.vis-item.work-to-do-item{class: "#{visible_status(task)} #{'doable' if task.doable?(current_user)}", data: {'task-id'=>task.id}}
      = "#{task.relative_id}) #{task.name} #{task.waitings_to_s}"
      %br
      %small
        = task.address
        = " | coordinates: (#{task.latitude.round(3)}, #{task.longitude.round(3)})"

app/views/my_processes/edit.html.haml
.row
  .col-xs-12.col-md-8.col-md-offset-2
    %h1 Editing Process
    = render 'form'

app/views/my_processes/empty.haml
.empty
  %h1 There are no processes

app/views/my_processes/index.html.haml
%h1 Processes
.row
  .col-xs-12
    .list-group
      - @my_processes.each do |my_process|
        = link_to my_process, class: "list-group-item #{'active' if my_process == @my_process}" do
          = my_process.name
          - if my_process.status == 'finished'
            %i.small (finished)
          %br
          %small
            = "Created by: #{my_process.user}"
    = will_paginate @my_processes
-# %table.table
-#   %tr
-#     %th ID
-#     %th Process
-#     %th Hashtag
-#   - @my_processes.each do |my_process|
-#     %tr
-#       %td= link_to my_process.id, my_process
-#       %td= link_to my_process.name, my_process
-#       %td= link_to my_process.hashtag, my_process

app/views/my_processes/new.html.haml
.row
  .col-xs-12.col-sm-8.col-sm-offset-2
    %h1.center-text Create a new process

    = simple_form_for(@my_process) do |f|
      .form-inputs.mt-lg
        = f.input :name, label: 'Name this process'
        = f.input :hashtag, label: 'Give it a hashtag for identification'
      %hr
      .form-actions
        = f.button :submit, 'Submit', class: 'btn btn-primary btn-block'

app/views/my_processes/new_tasks.haml
.row
  .col-xs-12.col-sm-8.col-sm-offset-2
    %h1.center-text= "Add tasks involved in #{@my_process.name}"
    .mb-lg
    = simple_form_for @my_process, url: create_tasks_my_process_path(@my_process) do |f|
      .form-inputs
        = link_to_add_fields '+ Add Task', f, :tasks, {class: 'btn btn-default btn-block mt-lg'}
      %hr
      .form-actions
        = f.button :submit, 'Submit', class: 'btn btn-primary btn-block'

app/views/my_processes/show.html.haml
.container
  .row
    .col-sm-4
      .list-group
        - @my_processes.each do |my_process|
          = link_to my_process, class: "list-group-item #{'active' if my_process == @my_process}" do
            = my_process.name
            %br
            %small
              = "Created by: #{my_process.user}"            
    .col-sm-8
      = link_to '#', {"data-target" => "#my_process-modal-#{@my_process.id}", "data-toggle" => "modal", :type => "button", class: 'btn btn-xs btn-default pull-right'} do
        %i.glyphicon.glyphicon-pencil
        Edit
      = render 'shared/form_modal', object: @my_process
      %h1.no-margin= @my_process.name
      .row
        .col-xs-6
          %b Created by:
          = @my_process.user
        .col-xs-6
          %b Twitter status:
          = link_to "##{@my_process.hashtag}", @my_process.twitter_status_url, target: '_blank'
      .row.mt-lg
        .col-xs-12
          = render :partial => 'google_maps/map_with_searchbox', :locals => {:locations => @my_process.tasks_locations, :center => @my_process.tasks_center}
          = link_to 'add task', '#', {"data-target" => "#task-modal-0", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => 'add-task'}
          = render 'shared/form_modal', object: @my_process.tasks.new(id: 0)
          - @my_process.tasks.each do |task|
            = link_to 'edit task', '#', {"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => "edit-task-#{task.id}"}
            = render 'shared/form_modal', object: task
          .timeline.mt-lg
            = render 'timeline/timeline', timeline: @my_process.tasks_timeline
          .hidden
            %h2 Tasks
            - @my_process.tasks.order("assigned_start ASC").each do |task|
              .task.relative{id: "task-#{task.id}"}
                = link_to '#', {"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button"} do
                  %h3.no-margin= task.name
                %p= "Responsible: #{task.responsible_user || '-'}"
                .waitings.mb-md
                  Waiting for: 
                  - task.waitings.each do |waiting|
                    %span.label.label-default.mr-sm{id: "waiting-#{waiting.id}"}
                      = waiting.waiting.name
                      = link_to '#', class: 'white-link destroy-waiting', data: {id: waiting.id} do 
                        %i.glyphicon.glyphicon-remove
                = link_to '+ Wait for', new_waiting_path(task_id: task.id), class: 'btn btn-default btn-xxs'
                .top-right
                  = render 'shared/modal', task: task
                  %button.btn.btn-default.btn-xs{"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button", id: "edit-task-#{task.id}"}
                    Edit
                  = link_to task, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
                    %i.glyphicon.glyphicon-trash
                .clearfix

                    
          /= link_to '+ Add task', new_task_path(my_process_id: @my_process.id), class: 'btn btn-primary'        
          %h2 Messages
          %table.table
            %thead
              %tr
                %th Created at
                %th Sender
                %th Receiver
                %th Message
            %tbody
              - @my_process.messages.order('created_at ASC').each do |message|
                %tr
                  %td= message.created_at.strftime("%Y/%m/%d %H:%m")
                  %td= message.sender
                  %td= message.receiver
                  %td= message.message
          = link_to '+ Add message', new_message_path(my_process_id: @my_process.id)

app/views/my_processes/show_admin.haml
.row
  .col-sm-0#my-process-left-bar
    - @my_process.tasks.each do |task|
      .hidden.task-form{id: "task-#{task.id}-form"}
        = render 'tasks/form', task: task
  .col-xs-12#my-process-content
    .actions.pull-right
      = link_to '#', {"data-target" => "#my_process-modal-#{@my_process.id}", "data-toggle" => "modal", :type => "button", class: 'btn btn-xs btn-default'} do
        %i.glyphicon.glyphicon-pencil
        Edit
      = link_to finish_my_process_path(@my_process), {class: 'btn btn-xs btn-default', method: :patch, data: {:confirm => 'Are you sure?'}} do
        Finish
      = link_to my_process_path(@my_process), {class: 'btn btn-xs btn-danger', method: :delete, data: {:confirm => 'Are you sure?'}} do
        %i.glyphicon.glyphicon-trash
        Delete
    = render 'shared/form_modal', object: @my_process
    %h1.no-margin= @my_process.name
    .row
      .col-xs-6
        %b Created by:
        = @my_process.user
      .col-xs-6
        %b Twitter status:
        = link_to "##{@my_process.hashtag}", @my_process.twitter_status_url, target: '_blank'
    .row.mt-lg
      .col-xs-12
        = render :partial => 'google_maps/map_with_searchbox', :locals => {:pins => pins(@my_process.tasks), :center => @my_process.tasks_center}
        = link_to 'add task', '#', {"data-target" => "#task-modal-0", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => 'add-task'}
        = render 'shared/form_modal', object: @my_process.tasks.new(id: 0)
        - pins(@my_process.tasks).each do |pin|
          - if(pin[:task_count] > 1)
            = link_to 'pin', '#', {"data-target" => "#pin-modal-#{pin[:id]}", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => "pin-#{pin[:id]}"}
            = render 'shared/pin_modal', pin: pin
        .timeline.mt-lg
          .mb-md
            = link_to request.original_url, class: 'btn btn-primary btn-xs pull-right' do
              %i.glyphicon.glyphicon-refresh
              Refresh
            .clearfix
          = render 'timeline/timeline', tasks: @my_process.tasks, id: 'visualization'
          .mt-md
            .can-be-done.inline-block.mr-md Can be done
            .cannot-be-done.inline-block.mr-md In progress or waiting for other tasks to end
        .hidden
          %h2 Tasks
          - @my_process.tasks.order("assigned_start ASC").each do |task|
            .task.relative{id: "task-#{task.id}"}
              = link_to '#', {"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button"} do
                %h3.no-margin= task.name
              %p= "Responsible: #{task.responsible_user || '-'}"
              .waitings.mb-md
                Waiting for:
                - task.waitings.each do |waiting|
                  %span.label.label-default.mr-sm{id: "waiting-#{waiting.id}"}
                    = waiting.waiting.name
                    = link_to '#', class: 'white-link destroy-waiting', data: {id: waiting.id} do
                      %i.glyphicon.glyphicon-remove
              = link_to '+ Wait for', new_waiting_path(task_id: task.id), class: 'btn btn-default btn-xxs'
              .top-right
                = render 'shared/modal', task: task
                %button.btn.btn-default.btn-xs{"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button", id: "edit-task-#{task.id}"}
                  Edit
                = link_to task, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
                  %i.glyphicon.glyphicon-trash
              .clearfix
        %h2 Workflow
        - @my_process.tasks.order("assigned_start ASC").each do |task|
          %p= task.to_s.html_safe

app/views/my_processes/show_worker.haml
.row
  .col-xs-12
    = render 'my_processes/work_to_do'
    .mt-md
      .can-be-done.inline-block.mr-md Can be done
      .in-progress.inline-block.mr-md In progress
      .cannot-be-done.inline-block.mr-md Ended / Waiting other tasks
.row.mt-lg
  .col-sm-0#my-process-left-bar
    - @my_process.tasks.each do |task|
      .hidden.task-form{id: "task-#{task.id}-form"}
        = render 'tasks/form', task: task
  .col-sm-12#my-process-content
    = render :partial => 'google_maps/map', :locals => {:pins => pins(@my_process.tasks.visibles_for(current_user)), :center => @my_process.tasks_center}
    - pins(@my_process.tasks).each do |pin|
      - if(pin[:task_count] > 1)
        = link_to 'pin', '#', {"data-target" => "#pin-modal-#{pin[:id]}", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => "pin-#{pin[:id]}"}
        = render 'shared/pin_modal', pin: pin
    = link_to 'add task', '#', {"data-target" => "#task-modal-0", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => 'add-task'}
    = render 'shared/form_modal', object: @my_process.tasks.new(id: 0)
    - @my_process.tasks.each do |task|
      = link_to 'edit task', '#', {"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button", 'class' => 'hidden', 'id' => "edit-task-#{task.id}"}
      = render 'shared/form_modal', object: task
    .timeline.mt-lg
      .mb-md
        = link_to request.original_url, class: 'btn btn-primary btn-xs pull-right' do
          %i.glyphicon.glyphicon-refresh
          Refresh
        .clearfix
      = render 'timeline/timeline', tasks: @my_process.tasks, id: 'visualization'
    .hidden
      %h2 Tasks
      - @my_process.tasks.order("assigned_start ASC").each do |task|
        .task.relative{id: "task-#{task.id}"}
          = link_to '#', {"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button"} do
            %h3.no-margin= task.name
          %p= "Responsible: #{task.responsible_user || '-'}"
          .waitings.mb-md
            Waiting for:
            - task.waitings.each do |waiting|
              %span.label.label-default.mr-sm{id: "waiting-#{waiting.id}"}
                = waiting.waiting.name
                = link_to '#', class: 'white-link destroy-waiting', data: {id: waiting.id} do
                  %i.glyphicon.glyphicon-remove
          = link_to '+ Wait for', new_waiting_path(task_id: task.id), class: 'btn btn-default btn-xxs'
          .top-right
            = render 'shared/modal', task: task
            %button.btn.btn-default.btn-xs{"data-target" => "#task-modal-#{task.id}", "data-toggle" => "modal", :type => "button", id: "edit-task-#{task.id}"}
              Edit
            = link_to task, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              %i.glyphicon.glyphicon-trash
          .clearfix

app/views/my_processes/success.haml
.center-text
  %h1 Process created!
  Check progress with the hashtag 
  = link_to "##{@my_process.hashtag}", @my_process.twitter_status_url, target: '_blank'